#!/bin/sh
# Example boot script

PREREQ="mdadm" 

prereqs(){         
    echo "$PREREQ" 
}

. /scripts/functions

case $1 in 
    prereqs)
        prereqs
        exit 0
    ;; 
esac

# Begin real processing below this line 

log_begin_msg "Starting root-on-crypt"
/sbin/modprobe usb-storage
#[ -e /dev/mmcblk0 ] || mknod -m 0660 /dev/mmcblk0 b 179 0
sleep 10; # it takes a bit for sda to come online...
#Bus 004 Device 014: ID 0781:5406 SanDisk Corp. Cruzer Micro U3
[ ! -d /cryptkeys/boot ] && mkdir -p /cryptkeys/boot

case "$(uname -r)" in
  2.6.26-2-486)
    /bin/mount -t ext2 /dev/sdb1 /cryptkeys/boot
    ;;
  2.6.32-bpo.4-486)
    /bin/mount -t ext2 /dev/sda1 /cryptkeys/boot
    ;;
  2.6.39-net5501+)
    /bin/mount -t ext2 /dev/sdb1 /cryptkeys/boot
    ;;
  *)
    /bin/mount -t ext2 /dev/sdb1 /cryptkeys/boot
    ;;
esac

/bin/sh

# start all crypto volumes in /cryptkeys/boot/crypttab
if [ ! -f /cryptkeys/boot/crypttab ]; then 
    echo "could not read /cryptkeys/boot/crypttab"
    reboot; 
else
    /bin/cat /cryptkeys/boot/crypttab|awk '{print "cryptsetup --key-file /cryptkeys"$3" luksOpen "$2" "$1}'| \
        while read READY_DEVICE ; do
            echo "${READY_DEVICE}"
            ${READY_DEVICE}
        done
fi
/bin/umount /cryptkeys/boot

/bin/sh

#mount /dev/mapper/crypt_dev_hda2 /root
#ls /root
#echo "sleeping 3000"
#sleep 3000
exit 0
